# -*- coding: utf-8 -*-
"""catcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2w-i58wpYpF-A9D1J0WKwaXU-m0mtle

## 수비형 타자 vs 포수형 타자
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from matplotlib import rc
import platform

if platform.system() == 'Windows':
    rc('font', family='Malgun Gothic')
elif platform.system() == 'Darwin': # Mac
    rc('font', family='AppleGothic')
else: #linux
    rc('font', family='NanumGothic')

plt.rcParams['axes.unicode_minus'] = False

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv('/content/hitter_salary_stats_all.csv')
df2023= df[df['연도']==2023]

# df = df2020[['선수명','팀명','HR','RBI','연도','후년연봉']]
# df = df[df['팀명'] == '한화'].sort_values(by='HR',ascending=False)
# df1 = df.sort_values(by='RBI', ascending=False)

df2023.describe()

df2 = pd.read_csv('/content/defense.csv')
df2.sort_values(by='CS%', ascending=False, inplace=True)
df2.info()

df2 = df2[df2['연도']==2023]
df2

df2 = df2[['선수명','팀명','POS','CS%','연도']]

df3 = df2[df2['POS']=='포수']
df3[df3['선수명']=='양의지']

df2023 = df2023[['선수명','팀명','AVG','후년연봉']]
# df2021 = df2021.loc[df2021['선수명'] == '이재원', '후년연봉'] = 10000

result = pd.to_numeric(df3['후년연봉'], errors='coerce')
result = pd.merge(df3,df2023, on=['선수명'], how='inner')
result = result[['선수명','팀명_y','팀명_x','CS%','AVG','후년연봉','연도']]
condition = (result['선수명']=='이재원') & (result['팀명_y'] == 'LG') |(result['선수명']=='이재용')
result = result[~condition]
result
# result.loc[result['선수명'] == '이재원', '후년연봉'] = 10000
# result = result[result_d]
# result.to_csv('포수2022CS%.csv', index = False)

# result_new = pd.DataFrame([{'선수명':'양의지',
#               '팀명_y' : '두산',
#               '팀명_x' : 'NC',
#               'CS%' : '42.2',
#               'AVG' : '0.283',
#               '후년연봉' : '30000.0',
#               '연도':2022}])
# result = pd.concat([result,result_new], ignore_index = True)
# result

result['CS%'] = pd.to_numeric(result['CS%'], errors='coerce')
result3 = result.dropna(subset=['CS%'])
result3.sort_values(by='CS%', ascending=False, inplace=True)
result3 = result3[:10]
result3.to_csv('포수2023CS%.csv', index = False)
result3

df4 = pd.read_csv('/content/포수2020AVG.csv')
#df5 연도 바꿔가면서 실행
df5 = pd.read_csv('/content/포수2023CS%.csv')
df6 = pd.read_csv('/content/포수2020연봉.csv')

# fig = plt.figure(figsize = (10,6))
# ax = fig.add_subplot(1,1,1)

# ax.bar(df5['선수명'], df5['CS%'], color='r', label='도루저지율')

# ax.set_xlabel('선수명', fontsize=20)
# ax.set_ylabel('도루저지율', fontsize=20)

# ax.set_xlabel('선수명', fontsize = 20)

fig = plt.figure(figsize = (10,6))
ax = fig.add_subplot(1,1,1)

ax.bar(df5['선수명'], df5['AVG'], color='g', label='타율')

ax.set_xlabel('선수명', fontsize=20)
ax.set_ylabel('타율', fontsize=20)

fig = plt.figure(figsize = (10,6))
ax = fig.add_subplot(1,1,1)

ax.bar(df5['선수명'], df5['후년연봉'], color='b', label='후년연봉')

ax.set_xlabel('선수명', fontsize=20)
ax.set_ylabel('후년연봉', fontsize=20)

fig, axes = plt.subplots(nrows=3, ncols=1, figsize=(6, 18))

axes[0].bar(df5['선수명'], df5['CS%'], color='r', label='도루저지율')

axes[0].set_xlabel('선수명', fontsize=10)
axes[0].set_ylabel('도루저지율', fontsize=10)

axes[1].bar(df5['선수명'], df5['AVG'], color='g', label='타율')

axes[1].set_xlabel('선수명', fontsize=10)
axes[1].set_ylabel('타율', fontsize=10)

axes[2].bar(df5['선수명'], df5['후년연봉'], color='b', label='후년연봉')

axes[2].set_xlabel('선수명', fontsize=10)
axes[2].set_ylabel('후년연봉', fontsize=10)

