# -*- coding: utf-8 -*-
"""salary&rank relationship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2yauINZD5jxfCpdGgFAmMwk4_PXbDva
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

from matplotlib import rc
import platform
import matplotlib.pyplot as plt
import numpy as np


if platform.system() == 'Windows':
    rc('font', family='Malgun Gothic')
elif platform.system() == 'Darwin': # Mac
    rc('font', family='AppleGothic')
else: #linux
    rc('font', family='NanumGothic')

plt.rcParams['axes.unicode_minus'] = False

import pandas as pd

df = pd.read_csv('/content/hitter_salary_stats_all.csv')
# df1 = df[df['연도']==2020]
# df2 = df[df['연도']==2021]
# df3 = df[df['연도']==2022]
# df4 = df[df['연도']==2023]

yearly_sum = df.groupby(['연도','팀명']).sum().reset_index()
yearly_sum = yearly_sum[['팀명','연도','연봉(만원)']]

df_rank = pd.read_csv('/content/구단순위.csv', encoding='CP949')
df_rank

df1_r = df_rank[df_rank['연도']==2020]
df2_r = df_rank[df_rank['연도']==2021]
df3_r = df_rank[df_rank['연도']==2022]
df4_r = df_rank[df_rank['연도']==2023]

df_r_merge = pd.merge(df_rank,yearly_sum)
df1 = df_r_merge[df_r_merge['연도']==2020]
df2 = df_r_merge[df_r_merge['연도']==2021]
df3 = df_r_merge[df_r_merge['연도']==2022]
df4 = df_r_merge[df_r_merge['연도']==2023]

df1

df_r_merge['연봉순위'] = df_r_merge.groupby('연도')['연봉(만원)'].rank(ascending=False)
df2020 = df_r_merge[df_r_merge['연도']==2020]
df2020 = df2020.sample(frac=1).reset_index(drop=True)
df2020
df2020.to_csv('연봉순위.csv', index=False)

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.set_xlabel('팀명')
ax1.set_ylabel('순위', color='tab:blue')
ax1.plot(df2020['팀명'], df2020['순위'], marker='o', color='tab:blue', label='순위')
ax1.invert_yaxis()
ax1.tick_params(axis='y', labelcolor='tab:blue')

ax2 = ax1.twinx()
ax2.set_ylabel('연봉 순위', color='tab:red')
ax2.plot(df2020['팀명'], df2020['연봉순위'], marker='o', color='tab:red', label='연봉 순위')
ax2.invert_yaxis()
ax2.tick_params(axis='y', labelcolor='tab:red')

plt.title('팀별 연도별 순위 및 연봉 순위 변화')
ax1.set_xticks(df2020['팀명'])
ax1.set_xticklabels(df2020['팀명'], rotation=45, ha='right')

fig.tight_layout()
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))

plt.show()

df_r_merge['연봉순위'] = df_r_merge.groupby('연도')['연봉(만원)'].rank(ascending=False)
df2021 = df_r_merge[df_r_merge['연도']==2021]
df2021

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.set_xlabel('팀명')
ax1.set_ylabel('순위', color='tab:blue')
ax1.plot(df2021['팀명'], df2021['순위'], marker='o', color='tab:blue', label='순위')
ax1.invert_yaxis()
ax1.tick_params(axis='y', labelcolor='tab:blue')

ax2 = ax1.twinx()
ax2.set_ylabel('연봉 순위', color='tab:red')
ax2.plot(df2021['팀명'], df2021['연봉순위'], marker='o', color='tab:red', label='연봉 순위')
ax2.invert_yaxis()
ax2.tick_params(axis='y', labelcolor='tab:red')

plt.title('팀별 연도별 순위 및 연봉 순위 변화')
ax1.set_xticks(df2021['팀명'])
ax1.set_xticklabels(df2021['팀명'], rotation=45, ha='right')

fig.tight_layout()
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))

plt.show()

df_r_merge['연봉순위'] = df_r_merge.groupby('연도')['연봉(만원)'].rank(ascending=False)
df2022 = df_r_merge[df_r_merge['연도']==2022]
df2022

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.set_xlabel('팀명')
ax1.set_ylabel('순위', color='tab:blue')
ax1.plot(df2022['팀명'], df2022['순위'], marker='o', color='tab:blue', label='순위')
ax1.invert_yaxis()
ax1.tick_params(axis='y', labelcolor='tab:blue')

ax2 = ax1.twinx()
ax2.set_ylabel('연봉 순위', color='tab:red')
ax2.plot(df2022['팀명'], df2022['연봉순위'], marker='o', color='tab:red', label='연봉 순위')
ax2.invert_yaxis()
ax2.tick_params(axis='y', labelcolor='tab:red')

plt.title('팀별 연도별 순위 및 연봉 순위 변화')
ax1.set_xticks(df2022['팀명'])
ax1.set_xticklabels(df2022['팀명'], rotation=45, ha='right')

fig.tight_layout()
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))

plt.show()

df_r_merge['연봉순위'] = df_r_merge.groupby('연도')['연봉(만원)'].rank(ascending=False)
df2023 = df_r_merge[df_r_merge['연도']==2023]
df2023

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.set_xlabel('팀명')
ax1.set_ylabel('순위', color='tab:blue')
ax1.plot(df2023['팀명'], df2023['순위'], marker='o', color='tab:blue', label='순위')
ax1.invert_yaxis()
ax1.tick_params(axis='y', labelcolor='tab:blue')

ax2 = ax1.twinx()
ax2.set_ylabel('연봉 순위', color='tab:red')
ax2.plot(df2023['팀명'], df2023['연봉순위'], marker='o', color='tab:red', label='연봉 순위')
ax2.invert_yaxis()
ax2.tick_params(axis='y', labelcolor='tab:red')

plt.title('팀별 연도별 순위 및 연봉 순위 변화')
ax1.set_xticks(df2023['팀명'])
ax1.set_xticklabels(df2023['팀명'], rotation=45, ha='right')

fig.tight_layout()
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))

plt.show()

df_r_merge = df_r_merge.sample(frac=1).reset_index(drop=True)

team_order = df_r_merge['팀명'].unique()

years = [2020, 2021, 2022, 2023]
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

for i, year in enumerate(years):
    df_year = df_r_merge[df_r_merge['연도'] == year]
    ax = axes[i // 2, i % 2]

    df_year = df_year.set_index('팀명').reindex(team_order).reset_index()

    ax.plot(df_year['팀명'], df_year['순위'], marker='o', color='tab:blue', label='순위')
    ax.invert_yaxis()
    ax.set_xlabel('팀명')
    ax.set_ylabel('순위')
    ax.legend(loc='upper left')
    ax.set_title(f'{year}년 순위와 연봉 순위')

    ax2 = ax.twinx()
    ax2.invert_yaxis()
    ax2.plot(df_year['팀명'], df_year['연봉순위'], marker='o', color = 'tab:red', label='연봉 순위')
    ax2.legend(loc='upper right')

fig.tight_layout()
plt.show()

df_r_merge['연봉순위'] = df_r_merge.groupby('연도')['연봉(만원)'].rank(ascending=False)
df_rank_yearn = df_r_merge[df_r_merge['팀명']=='NC']
df_rank_yearn = df_rank_yearn.sort_values(by = ['연도'])
df_rank_yearn

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.set_xlabel('NC')
ax1.set_ylabel('순위', color='tab:blue')
ax1.plot(df_rank_yearn['연도'], df_rank_yearn['순위'], marker='o', color='tab:blue', label='순위')
ax1.tick_params(axis='y', labelcolor='tab:blue')
ax1.set_ylim(0,11)
ax1.invert_yaxis()

ax2 = ax1.twinx()
ax2.set_ylabel('연봉 순위', color='tab:red')
ax2.plot(df_rank_yearn['연도'], df_rank_yearn['연봉순위'], marker='o', color='tab:red', label='연봉 순위')
ax2.tick_params(axis='y', labelcolor='tab:red', right=False)
ax2.set_yticks([])
ax2.set_ylim(0,11)
ax2.invert_yaxis()

plt.title('팀별 연도별 순위 및 연봉 순위 변화')
ax1.set_xticks(df_rank_yearn['연도'])
ax1.set_xticklabels(df_rank_yearn['연도'], rotation=45, ha='right')

fig.tight_layout()
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))

plt.show()

df_r_merge['연봉순위'] = df_r_merge.groupby('연도')['연봉(만원)'].rank(ascending=False)
df_rank_yearh = df_r_merge[df_r_merge['팀명']=='한화']
df_rank_yearh = df_rank_yearh.sort_values(by = ['연도'])
df_rank_yearh

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.set_xlabel('한화')
ax1.set_ylabel('순위', color='tab:blue')
ax1.plot(df_rank_yearh['연도'], df_rank_yearh['순위'], marker='o', color='tab:blue', label='순위')
ax1.tick_params(axis='y', labelcolor='tab:blue')
ax1.set_ylim(0,11)
ax1.invert_yaxis()

ax2 = ax1.twinx()
ax2.set_ylabel('연봉 순위', color='tab:red')
ax2.plot(df_rank_yearh['연도'], df_rank_yearh['연봉순위'], marker='o', color='tab:red', label='연봉 순위')
ax2.tick_params(axis='y', labelcolor='tab:red', right=False)
ax2.set_ylim(0,11)
ax2.invert_yaxis()

plt.title('팀별 연도별 순위 및 연봉 순위 변화')
ax1.set_xticks(df_rank_yearh['연도'])
ax1.set_xticklabels(df_rank_yearh['연도'], rotation=45, ha='right')

fig.tight_layout()
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))

plt.show()

df_r_merge['연봉순위'] = df_r_merge.groupby('연도')['연봉(만원)'].rank(ascending=False)
df_rank_years = df_r_merge[df_r_merge['팀명']=='KT']
df_rank_years = df_rank_years.sort_values(by = ['연도'])
df_rank_years

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.set_xlabel('KT')
ax1.set_ylabel('순위', color='tab:blue')
ax1.plot(df_rank_years['연도'], df_rank_years['순위'], marker='o', color='tab:blue', label='순위')
ax1.tick_params(axis='y', labelcolor='tab:blue')
ax1.set_ylim(0,11)
ax1.invert_yaxis()

ax2 = ax1.twinx()
ax2.set_ylabel('연봉 순위', color='tab:red')
ax2.plot(df_rank_years['연도'], df_rank_years['연봉순위'], marker='o', color='tab:red', label='연봉 순위')
ax2.tick_params(axis='y', right=False)
ax2.set_ylim(0,11)
ax2.invert_yaxis()

plt.title('팀별 연도별 순위 및 연봉 순위 변화')
ax1.set_xticks(df_rank_years['연도'])
ax1.set_xticklabels(df_rank_years['연도'], rotation=45, ha='right')

fig.tight_layout()
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))

plt.show()

df_r_merge['연봉순위'] = df_r_merge.groupby('연도')['연봉(만원)'].rank(ascending=False)
df_rank_year = df_r_merge
#df_rank_year = df_r_merge[df_r_merge['팀명']=='SSG']
df_rank_year = df_rank_year.sort_values(by = ['연도'])
#df_rank_year

from matplotlib.lines import Line2D
teams = df_rank_year['팀명'].unique()

fig, axes = plt.subplots(2, 5, figsize=(20, 10))
fig.suptitle('팀별 연도별 순위 및 연봉 순위 변화', fontsize=16)

for i, team in enumerate(teams):
    ax1 = axes[i // 5, i % 5]
    team_data = df_rank_year[df_rank_year['팀명'] == team].sort_values(by='연도', ascending=False)

    ax1.set_xlabel('연도')
    ax1.set_ylabel('순위')
    ax1.plot(team_data['연도'], team_data['순위'], marker='o', color='tab:blue', label='순위')
    ax1.set_ylim(0, 11)
    ax1.invert_yaxis()

    ax2 = ax1.twinx()
    ax2.plot(team_data['연도'], team_data['연봉순위'], marker='o', color='tab:red', label='연봉 순위')
    ax2.set_ylim(0, 11)
    ax2.invert_yaxis()

    ax1.set_title(f'{team}')
    ax1.set_xticks(team_data['연도'])
    ax1.set_xticklabels(team_data['연도'], rotation=45, ha='right')

legend_elements = [Line2D([0], [0], color='tab:blue', marker='o', label='순위'),
                   Line2D([0], [0], color='tab:red', marker='o', label='연봉 순위')]

fig.legend(handles=legend_elements, loc='upper left', bbox_to_anchor=(0.1, 0.97))

fig.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()



